CREATE TABLE IF NOT EXISTS tasks
(

    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          UUID NOT NULL,
    task_status       INTEGER NOT NULL,
    processing_step   INTEGER NOT NULL,
    attempts          INTEGER,
    next_attempt_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL,
    updated_at        TIMESTAMPTZ NOT NULL

);

CREATE INDEX IF NOT EXISTS idx_tasks_order_id on tasks(order_id);
CREATE INDEX IF NOT EXISTS idx_tasks_next_attempt on tasks(task_status,next_attempt_at);

ALTER TABLE tasks
    ADD CONSTRAINT fk_tasks_order_id
    FOREIGN KEY (order_id)
    REFERENCES orders (id)
    ON DELETE CASCADE;