

services:
  postgres:
    image: postgres:18
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

  payment-stub:
    image: payment-stub:latest
    build:
      context: ..
      dockerfile: payment-stub/Dockerfile
    environment:
      SERVER_PORT: 8084
    ports:
      - "8084:8084"

volumes:
  pgdata:
    external: true